name: Push to other

on:
  push:
    branches-ignore:
      - master
      - release/*

jobs:
  labels:
    name: Update repo labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Update labels - dry run
        uses: crazy-max/ghaction-github-labeler@v1
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build image
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          TERM: xterm-256color
        run: make build

  pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Create pull request - dependency (conditional)
        if: startsWith(github.ref, 'refs/heads/dependency')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,dependency
          template: .github/PULL_REQUEST_TEMPLATE/DEPENDENCY.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - bugfix (conditional)
        if: startsWith(github.ref, 'refs/heads/bugfix')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,bugfix
          template: .github/PULL_REQUEST_TEMPLATE/BUGFIX.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - feature (conditional)
        if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: "${{ github.actor }}"
          label: automatic,feature
          template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - documentation (conditional)
        if: startsWith(github.ref, 'refs/heads/documentation')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,documentation
          template: .github/PULL_REQUEST_TEMPLATE/DOCUMENTATION.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - other (conditional)
        if: startsWith(github.ref, '!refs/heads/dependency') && startsWith(github.ref, '!refs/heads/bugfix') && startsWith(github.ref, '!refs/heads/feature') && startsWith(github.ref, '!refs/heads/documentation')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,feature
          template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
